# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 836d648f43c5c9e0745746c8999ef53f7444db98b9d4c3eee84abf32e9791dcd22967c6fb1f26ff2912bd5fe2355832daf7914ac44de655887ef009b61a5749a

test:
  secret_key_base: e486dcc7e047f6a56be62d0175f3f827ca038a698938b0698496a7c779c1e11bc30b001aed5d0c4cd84256a75080f79a974c672c980e7505509c792c2886858b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
